GENDER_CHOICES = [
    ("", "Select Gender"),
    ("Male", "Male"),
    ("Female", "Female"),
    ("Other", "Other"),
]
BLOOD_GROUP_CHOICES = [
    ("", "Select Blood Group"),
    ("A+", "A+"),
    ("A-", "A-"),
    ("B+", "B+"),
    ("B-", "B-"),
    ("AB+", "AB+"),
    ("AB-", "AB-"),
    ("O+", "O+"),
    ("O-", "O-"),
]
STATUS_CHOICES = [
    ("", "Select Status"),
    ("P", "Pending"),
    ("C", "Completed"),
    ("I", "In Progress"),
    ("R", "Rejected"),
]
TYPES_CHOICES = [
    ("", "Select Ambulance Type"),
    ("Standard", "Standard"),
    ("AC", "AC"),
    ("Cardiac", "Cardiac"),
    ("ICU", "ICU"),
    ("Freezer", "Freezer"),
]
CITY_CHOICES = [
    ("", "Select City"),
    ("Bagerhat", "Bagerhat"),
    ("Bandarban", "Bandarban"),
    ("Barguna", "Barguna"),
    ("Barishal", "Barishal"),
    ("Bhola", "Bhola"),
    ("Bogura", "Bogura"),
    ("Brahmanbaria", "Brahmanbaria"),
    ("Chandpur", "Chandpur"),
    ("Chapainawabganj", "Chapainawabganj"),
    ("Chattogram", "Chattogram"),
    ("Chuadanga", "Chuadanga"),
    ("Cox’s Bazar", "Cox’s Bazar"),
    ("Cumilla", "Cumilla"),
    ("Dhaka", "Dhaka"),
    ("Dinajpur", "Dinajpur"),
    ("Faridpur", "Faridpur"),
    ("Feni", "Feni"),
    ("Gaibandha", "Gaibandha"),
    ("Gazipur", "Gazipur"),
    ("Gopalganj", "Gopalganj"),
    ("Habiganj", "Habiganj"),
    ("Jamalpur", "Jamalpur"),
    ("Jashore", "Jashore"),
    ("Jhalokati", "Jhalokati"),
    ("Jhenaidah", "Jhenaidah"),
    ("Joypurhat", "Joypurhat"),
    ("Khagrachhari", "Khagrachhari"),
    ("Khulna", "Khulna"),
    ("Kishoreganj", "Kishoreganj"),
    ("Kushtia", "Kushtia"),
    ("Kurigram", "Kurigram"),
    ("Lakshmipur", "Lakshmipur"),
    ("Lalmonirhat", "Lalmonirhat"),
    ("Madaripur", "Madaripur"),
    ("Magura", "Magura"),
    ("Manikganj", "Manikganj"),
    ("Meherpur", "Meherpur"),
    ("Moulvibazar", "Moulvibazar"),
    ("Munshiganj", "Munshiganj"),
    ("Mymensingh", "Mymensingh"),
    ("Naogaon", "Naogaon"),
    ("Narayanganj", "Narayanganj"),
    ("Narail", "Narail"),
    ("Narsingdi", "Narsingdi"),
    ("Natore", "Natore"),
    ("Netrokona", "Netrokona"),
    ("Nilphamari", "Nilphamari"),
    ("Noakhali", "Noakhali"),
    ("Pabna", "Pabna"),
    ("Panchagarh", "Panchagarh"),
    ("Patuakhali", "Patuakhali"),
    ("Pirojpur", "Pirojpur"),
    ("Rajbari", "Rajbari"),
    ("Rajshahi", "Rajshahi"),
    ("Rangamati", "Rangamati"),
    ("Rangpur", "Rangpur"),
    ("Satkhira", "Satkhira"),
    ("Shariatpur", "Shariatpur"),
    ("Sherpur", "Sherpur"),
    ("Sirajganj", "Sirajganj"),
    ("Sunamganj", "Sunamganj"),
    ("Sylhet", "Sylhet"),
    ("Tangail", "Tangail"),
    ("Thakurgaon", "Thakurgaon"),
]
